language: php

sudo: false

php:
  - 7.0

before_script:
  - sh -c "composer require 'cakephp/cakephp-codesniffer:dev-master'"
  - vendor/bin/phpunit tests/TestCase/Controller/RoutesControllerTest.php
  - vendor/bin/phpunit tests/TestCase/Controller/UsersControllerTest.php

  - composer install
  - phpenv rehash

script:
  - sh -c "vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./webroot"
notifications:
  email: false
