language: php

sudo: false

php:
  - 7.0

before_script:
  - sh -c "composer require 'cakephp/cakephp-codesniffer:dev-master'"
  - phpenv rehash

script:
  - sh -c "vendor/bin/phpcs -p --extensions=php ./src ./tests ./config ./webroot"

notifications:
  email: false
